config_version = 13

[audio]
enable_sounds = true

[bar.default]
background_opacity = 0.74999998323619366
capsule_radius = 8
center = [ "nix-monitor", "bar", "spacer_2", "clock", "spacer_2", "status", "bar_2", "recorder" ]
end = [
    "media",
    "audio_visualizer",
    "tray",
    "volume",
    "network",
    "bluetooth",
    "brightness",
    "battery",
    "keyboard_layout",
    "notifications"
]
margin_edge = 8
margin_ends = 8
radius = 16
shadow = false
start = [ "launcher", "workspaces", "layout", "window" ]

[battery.device."/org/freedesktop/UPower/devices/battery_hidpp_battery_0"]
warning_threshold = 10

[brightness]
enable_ddcutil = true
sync_all_monitors = true

[control_center]
sidebar_section = "none"

    [control_center.calendar]
    show_events_card = false

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "wallpaper"

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
auto_hide = true
border_width = 1.0
reserve_space = false
shadow = false

[hooks]
session_unlocked = "mmsg dispatch reload_config"

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[keybinds]
down = [ "down", "ctrl+n", "ctrl+j" ]
up = [ "up", "ctrl+p", "ctrl+k" ]

[location]
address = "Zelenogradsk, Russia"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-3", "lockscreen-login-box@HDMI-A-2", "lockscreen-login-box@DP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 960.0
    cy = 961.0
    output = "DP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2"]
    box_height = 196.0
    box_width = 720.0
    cx = 960.0
    cy = 961.0
    output = "HDMI-A-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-3"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 889.5
    output = "HDMI-A-3"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-3".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[nightlight]
enabled = true
force = true
temperature_night = 4500

[osd.kinds]
keyboard_layout = false
media = false
privacy = false

[plugin_settings."avivbintangaringga/nix-monitor"]
panel_placement = "floating"

[plugin_settings."blackbartblues/keymap"]
compositor = "mangowc"
mangowc_config = "/home/metsker/dotfiles/config/mango/config.conf"

[plugin_settings."ezequiel/mango_layouts"]
panel_position = "auto"

[plugin_settings."felipeartur/ai-usagebar"]
panel_open_near_click = true
panel_placement = "floating"

[plugin_settings."metsker/mango-layout"]
corner_roundness = 0.0
picker_placement = "floating"

[plugin_settings."noctalia/screen_recorder"]
audio_source = "default_output"
hide_inactive = true
video_source = "portal"

[plugin_settings."noctalia/timer"]
panel_placement = "floating"

[plugin_settings."noctalia/wallhaven"]
browser_placement = "floating"

[plugins]
enabled = [
    "noctalia/screen_recorder",
    "noctalia/wallhaven",
    "noctalia/timer",
    "metsker/mango-layout",
    "avivbintangaringga/nix-monitor",
    "gabedunn/voxtype",
    "felipeartur/ai-usagebar",
    "metsker/window-info"
]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

    [[plugins.source]]
    kind = "path"
    location = "/home/metsker/dotfiles/config/noctalia/plugins"
    name = "local"

[shell]
avatar_path = "/home/metsker/Chest/Media/pics/a staff/4444.jpg"
corner_radius_scale = 0.0
font_family = "JetBrainsMono Nerd Font"
launch_apps_as_systemd_services = true
polkit_agent = true

    [shell.launcher]
    categories = false

    [shell.panel]
    control_center_placement = "floating"
    open_near_click_control_center = true
    session_placement = "floating"
    shadow = false
    transparency_mode = "soft"
    wallpaper_placement = "floating"

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    command = "uwsm stop"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "5"
    variant = "destructive"

[theme]
builtin = "Ayu"
community_palette = "Atuel"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "foot", "gtk3", "gtk4", "kcolorscheme", "mango" ]
    community_ids = [ "zen-browser", "neovim", "papirus-icons", "yazi" ]

        [theme.templates.user.monstar]
        input_path = "/home/metsker/dotfiles/config/noctalia/templates/monstar"
        output_path = "~/.config/monstar/themes/noctalia"
        post_hook = "pkill -USR1 monstar 2>/dev/null || true"

[wallpaper.default]
path = "/home/metsker/Pictures/Wallpapers/wallhaven-2em38y.jpg"

[wallpaper.last]
path = "/home/metsker/Pictures/Wallpapers/wallhaven-2em38y.jpg"

[wallpaper.monitors.DP-1]
path = "/home/metsker/Pictures/Wallpapers/wallhaven-2em38y.jpg"

[wallpaper.monitors.HDMI-A-2]
path = "/home/metsker/Pictures/Wallpapers/wallhaven-2em38y.jpg"

[wallpaper.monitors.HDMI-A-3]
path = "/home/metsker/Pictures/Wallpapers/wallhaven-2em38y.jpg"

[[wallpaper.favorite]]
palette_source = "wallpaper"
path = "/home/metsker/Pictures/Wallpapers/wallhaven-qrjww5.jpg"
theme_mode = "dark"
wallpaper_scheme = "m3-content"

[[wallpaper.favorite]]
builtin_palette = "Ayu"
palette_source = "builtin"
path = "/home/metsker/Pictures/Wallpapers/wallhaven-x6128o.jpg"
theme_mode = "dark"

[widget.bar]
show_idle_on_horizontal = false
type = "noctalia/timer:bar"

[widget.bar_2]
extras = "none"
show_glyph = false
show_value = false
type = "felipeartur/ai-usagebar:bar"
visualization = "gauge"

[widget.clock]
format = "{:%b %d, %H:%M}"

[widget.launcher]
glyph = "noctalia"

[widget.layout]
type = "metsker/mango-layout:layout"

[widget.media]
hide_when_no_media = true
title_scroll = "on_hover"

    [widget.media.actions]
    left = "media toggle"
    right = "panel-toggle control-center media"

[widget.network]
show_label = false

[widget.nix-monitor]
colorize_glyph = false
show_text = false
type = "avivbintangaringga/nix-monitor:nix-monitor"
up_to_date_glyph = "heart-check"

[widget.notifications]
enabled = false

[widget.recorder]
enabled = true
type = "noctalia/screen_recorder:recorder"

[widget.spacer_2]
enabled = true
type = "spacer"

[widget.status]
idle_glyph = "microphone-mute"
recording_glyph = "bluetooth-device-microphone"
stopped_glyph = "microphone-mute"
streaming_glyph = "bluetooth-device-microphone"
type = "gabedunn/voxtype:status"

[widget.tray]
detached_panel = true
drawer = true

[widget.volume.actions]
scroll_down = "volume-down 1"
scroll_up = "volume-up 1"

[widget.window]
type = "metsker/window-info:window"

[widget.workspaces]
enabled = true
focused_output_only = true
show_labels = false