[general]
autostart = [
  "$TERMINAL --app-id herdr -e herdr",
  "Telegram",
  "discord",
  "spotify",
  "obsidian",
]

[[window_rule]]
match.app_id = "^org[.]telegram[.]desktop$"
match.at_startup = true
default_output = "DP-1"
default_workspace = 2
default_focused = false

[[window_rule]]
match.app_id = "^discord$"
match.at_startup = true
default_output = "DP-1"
default_workspace = 2
default_focused = false

[[window_rule]]
match.app_id = "^spotify$"
match.at_startup = true
default_output = "DP-1"
default_workspace = 3
default_focused = false

[[window_rule]]
match.app_id = "^herdr$"
match.at_startup = true
default_output = "DP-1"
default_workspace = 1
default_focused = false

[[window_rule]]
match.app_id = "^md[.]obsidian[.]Obsidian$"
match.at_startup = true
default_output = "HDMI-A-3"
default_workspace = 1
default_focused = false
