gui:
  theme:
    activeBorderColor:
      - "#92d69a"
      - bold
    inactiveBorderColor:
      - "#b2ceb1"
    searchingActiveBorderColor:
      - "#a9c7ff"
      - bold
    optionsTextColor:
      - "#c0c9bd"
    selectedLineBgColor:
      - "#c0c9bd"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#c0c9bd"
    cherryPickedCommitBgColor:
      - "#a9c7ff"
    markedBaseCommitFgColor:
      - "#a9c7ff"
    markedBaseCommitBgColor:
      - "#ffb4ab"
    unstagedChangesColor:
      - "#ffb4ab"
    defaultFgColor:
      - "#e0e3dc"
  border: single
