source=~/.config/mango/monitors.conf
source=~/.config/mango/appearance.conf
source=~/.config/mango/input.conf
source=~/.config/mango/layouts.conf
source=~/.config/mango/autostart.conf
source=~/.config/mango/rules.conf
source=~/.config/mango/keybinds.conf
source=~/.config/mango/noctalia.conf

# ---- Misc ----
xwayland_persistence=1
