sloppyfocus=1
warpcursor=1
focus_on_activate=1
focus_cross_monitor=1

# Keyboard
repeat_rate=25
repeat_delay=600
xkb_rules_layout=us,ru
xkb_rules_options=caps:escape,grp:ctrl_space_toggle

# Trackpad / Mouse
tap_to_click=1
tap_and_drag=1
disable_while_typing=1
trackpad_natural_scrolling=1
mouse_natural_scrolling=0
cursor_hide_timeout=5
cursor_theme=Adwaita
cursor_size=24
