# Scrolling
scroller_structs = 8
scroller_prefer_overspread = 1
scroller_default_proportion = 0.5
scroller_ignore_proportion_single = 0
scroller_proportion_preset=1.0,0.75,0.5
edge_scroller_pointer_focus=0

#Master
default_mfact=0.5

center_master_overspread=1
center_when_single_stack=0
