# Window rules
windowrule=isfloating:1,width:0.75,height:0.75,appid:com.gabm.satty
windowrule=isfloating:1,width:0.75,height:0.75,appid:mpv
windowrule=isfloating:1,width:0.75,height:0.75,appid:imv
windowrule=isfloating:1,appid:^[Ss]team$,title:^(?!Steam$)
windowrule=isfloating:1,width:0.75,height:0.75,appid:dev.noctalia.Noctalia
windowrule=isfloating:1,isnosizehint:1,appid:AmneziaVPN
windowrule=isfloating:1,appid:org.telegram.desktop,title:Media viewer
windowrule=isfloating:1,title:Select Folder
windowrule=isfloating:1,appid:zen,title:Library
windowrule=isfloating:1,appid:engrampa
windowrule=isfloating:1,title:^[Rr]ename

# isopensilent:1 = open without stealing focus (autostart apps)
windowrule=tags:2,monitor:DP-1,isopensilent:1,appid:org.telegram.desktop,title:^(?!Media viewer$)
windowrule=tags:2,monitor:DP-1,isopensilent:1,appid:discord
# windowrule=tags:3,monitor:DP-1,isopensilent:1,appid:music.youtube.com
windowrule=tags:1,monitor:HDMI-A-3,isopensilent:1,appid:soundcloud
windowrule=tags:1,monitor:DP-1,isopensilent:1,appid:^herdr$
windowrule=tags:4,monitor:DP-1,isopensilent:1,appid:notes.metsker.dev__brain

# Layer rules
layerrule=noanim:1,noblur:1,layer_name:selection
layerrule=noanim:1,noblur:1,layer_name:wayfreeze
layerrule=noanim:1,noblur:1,layer_name:hyprpicker

# Tag rules
tagrule=id:1,layout_name:right_tile
tagrule=id:2,layout_name:right_tile
tagrule=id:3,layout_name:right_tile
tagrule=id:4,layout_name:right_tile
tagrule=id:5,layout_name:right_tile
tagrule=id:6,layout_name:right_tile
tagrule=id:7,layout_name:right_tile
tagrule=id:8,layout_name:right_tile
tagrule=id:9,layout_name:right_tile
