# Window rules
windowrule=isfloating:1,width:0.75,height:0.75,appid:com.gabm.satty
windowrule=isfloating:1,width:0.75,height:0.75,appid:mpv
windowrule=isfloating:1,width:0.75,height:0.75,appid:imv
windowrule=isfloating:1,isnosizehint:1,appid:AmneziaVPN
windowrule=scroller_proportion:0.75,appid:dev.noctalia.Noctalia
windowrule=isfloating:1,appid:^[Ss]team$,title:^(?!Steam$)

windowrule=tags:2,monitor:DP-1,appid:org.telegram.desktop
windowrule=tags:2,monitor:DP-1,appid:discord
windowrule=tags:3,monitor:DP-1,appid:youtube-music
windowrule=tags:4,monitor:DP-1,appid:brain

# Layer rules
layerrule=noanim:1,noblur:1,layer_name:selection
layerrule=noanim:1,noblur:1,layer_name:wayfreeze
layerrule=noanim:1,noblur:1,layer_name:hyprpicker

# Tag rules
tagrule=id:1,layout_name:scroller
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:scroller
tagrule=id:4,layout_name:scroller
tagrule=id:5,layout_name:scroller
tagrule=id:6,layout_name:scroller
tagrule=id:7,layout_name:scroller
tagrule=id:8,layout_name:scroller
tagrule=id:9,layout_name:scroller
